name: 'Enforce Issue Number in PR Title'

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check title
        uses: actions/checkout@v2
      - name: Verify issue number in PR title
        run: |
          if ! [[ "${{ github.event.pull_request.title }}" =~ #[0-9]+ ]]; then
            echo "PR title does not contain an issue number!"
            exit 1
          fi
